### ISSUE TITLE
MVP 1: Account creation, login, and demo login

### ISSUE THREAD

**Issue by rexbodoia** [rexbodoia/CoinCenter#2]
There were two separate forms for sign in and sign up which were completely different, which was a lot of work but I have both working and polished the way I want them

**Comment by d-webs** [comment]
Everything looks good! One man piece of feedback: Did you notice that the font and overall size of the sign-up form is way bigger than your login form? You should be reusing a lot of the CSS classes to make this easier; this is why making reusable components is helpful!

Fix this and I'll check it off
